# Generated by Django 3.0 on 2021-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210709_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default.jpeg', upload_to='profilepic'),
        ),
    ]
