# Generated by Django 3.0 on 2021-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210712_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepic/default.jpeg', upload_to='profilepic'),
        ),
    ]
